### PR TITLE
Min 14

### PR DESCRIPTION
**Pull request by arsalanfardi**
**Timeline component slider**

Implemented timeline slider using Material-UI component. Styled to match mock-ups as closely as possible. Users can select discrete values of dates (current, 1 day, 1 week, 1 month, 1 year) from the slider to view historical data in addition to live data. Added the component to the home page fixed at bottom of screen - responsive and mobile compatible. 

**Centering of lines on thumb component fixed, screenshots updated.**

Screenshots attached.
timeline-1b
timeline-2b

### CODE REVIEW

**Comment by evan-krul** [comment]
Can you add some screenshots of the timeline?

**Comment by arsalanfardi** [comment]
@evan-krul Edited the PR to attach screenshots.

**Comment by evan-krul** [comment]
The double bars in the bubble of the component. Do they seem off-center to you?

**Review by evan-krul — APPROVED** [review]
Just fix the offset and its good.

**Comment by arsalanfardi** [comment]
Fixed offset, updated screenshots.

**Pull request merged**
